"""initial schema

Revision ID: 2902f5e310ca
Revises: 
Create Date: 2025-05-28 12:16:19.868900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2902f5e310ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('course_id', sa.VARCHAR(), nullable=False),
    sa.Column('upload_time', sa.DATETIME(), nullable=True),
    sa.Column('num_chunks', sa.INTEGER(), nullable=True),
    sa.Column('filepath', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
